name: sis_cv_api
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pillow
  - flask
  - flask-cors
  - tensorflow
  - matplotlib
#  - cudatoolkit
#  - cudnn
  - pip
  - pip:
    - opencv-python
    - mediapipe
    - ipykernel
