name: sis_cv_api
channels:
  - conda-forge
dependencies:
  - numpy
  - pandas
  - pillow
  - flask
  - flask-cors
  - tensorflow
  - matplotlib
  - ipywidgets
#  - cudatoolkit
#  - cudnn
  - pip
  - pip:
    - opencv-python
    - mediapipe
    - jupyter
    - ipykernel
    - websockets
    - asyncio
    - flask
    - flask_socketio
    - pyarrow
    - scikit-image
    - tqdm
    - pydot
    - redis==5.0.1
    - imutils
variables:
  SIS_DATASET_INPUT_PATH: "/Volumes/Public/Datasets/asl_fingerspelling"
  SIS_DATASET_PREPROC_PATH: "/Volumes/Public/Datasets/asl_fingerspelling_tfrec"
  API_SECRET: "this is definitely not a secret but oh well"
